services:
  - type: web
    name: parashu-frontend
    runtime: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /assets/*
        destination: /assets/*
      - type: rewrite
        source: /*
        destination: /index.html